export const Message = {
  ALREADY_EXIST: 'User already exit.',
  REGISTERED_SUCCESSFULLY: 'Congratulation! You are registered successfully..',
  MONGODB_CONNECTED: 'MongoDB Connected.',
  USER_LOGGED_IN_SUCCESSFULLY: 'User logged in successfully',
  USER_ALREADY_EXISTS: 'User already exists.',
  UNABLE_UP_USER:'Unable to update',
  REGISTRATION_ERROR: 'Registration error',
  PASSWORD_MISMATCH: 'password Mismatch',
  USER_NOT_FOUND: 'User not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  MONGODB_CONNECTION_ERROR: 'MongoDB Connection Error',
  NO_TOKEN: 'No token, authorization denied',
  TOKEN_IS_NOT_VALID: 'Token is not valid',
  LISTENING_TO_PORT: 'Listening to Port',
  SERVER_ERROR: 'Internal Server Error',
  PROFILE_UPDATED_SUCCESSFULLY: 'Profile updated successfully',
  NEW_PROFILE_CREATED_SUCCESSFULLY: 'New profile created successfully for user',
  MAIL_SENT: 'Mail sent successfully',
  UNABLE_SENT_MAIL:'Unable to sent to mail',
  OTP_MATCHED: 'Otp matched',
  OTP_NOT_MATCHED: 'Otp not matched',
  OTP_SEND: 'Otp sended successfuuly',
  PASS_UPDATED: 'Password updated successfully',
  INVALID_FILE_TYPE:'Invalid file type. Only JPG, JPEG, and PNG are allowed.',
  PROFILE_FETCHED_SUCCESSFULLY:'Profile fetched successfully for user',
  OLD_PASSWORD_INCORRECT:'Old password is incorrecct.',
  PASSWORD_CHANGE_SUCCESSFULLY:'Password successfully changed.',
  ERROR_ADDING_AAPLICANT:'Error adding applicant',
  ERROR_RETRIEVING_APPLICANTS:'Error retrieving applicants',
  APPLICANT_SUBMIT_SUCCESSFULLY:'Applicant Submit Successfully',
  FETCHED_ALL_APPLICANTS:'Fetched all applicants successfully.',
  FETCHED_APPLICANT_SUCCESSFULLY:'Fetched applicant successfully',
  APPLICANT_NOT_FOUND:'Applicant Not Found.',
  UPDATED_SUCCESSFULLY:'Updated Successfully.',
  ERROR_UPDATING_APPLICANT:'Error updating applicant',
  APPLICANT_DELETED_SUCCESSFULLY:'Applicant deleted successfully',
  ERROR_DELETING_APPLICANT:'Error deleting applicant',
  EMAIL_DELETED:'Email deleted successfully',
  SHOW_ALL_EMAILS:'Show all Emails',
  EMAIL_NOT_FOUND:'Email not found',
  FAILED_TO:'Failed to',
  OBJ_ID_NOT_FOUND:'ObjectId not found',
  FETCHED_DASHBOARD:'Fetched dashboard',
  ERROR_FETCHING_DASHBOARD:'error Fetching dashboard',
  FETCHING_STATES:'fetching states.',
  ERROR_FETCHING_COUNTRIES:'error fetching countries.',
  FETCHING_COUNTRIES:'fetching countries',
  ERROR_FETCHING_STATES:'error fetching states.',
  VIEW_ALL_PROFILE:'View all profiles',
  VIEW_SINGLE_PROFILE:'View Profile By id',
  NEW_YEAR: 'New year added successfully!!!!!',
  YEAR_NF: 'Year not found',
  YEAR_BY_ID: 'Get data by id',
  SHOW_YEARS: 'Show all years',
  YEAR_UP: 'Year updated successfully',
  YEAR_DEL: 'Deleted successfully',
  YEAR_NOT_FOUND:'Year not found'
};
