export const Enum = {
  ADMIN: 'admin',
  HR: 'hr',
  USER: 'user',
};
export const genderEnum = {
  MALE: 'male',
  FEMALE: 'female',
  OTHER: 'other',
};

export const applicantEnum = {
  YES: 'yes',
  NO: 'no',
  REMOTE: 'remote',
  HYBRID: 'hybrid',
  ONSITE: 'onsite',
  PENDING: 'pending',
  SELECTED: 'selected',
  REJECTED: 'rejected',
  HOLD: 'hold',
  IN_PROCESS: 'in-process',
  HR_ROUND: 'hr round',
  TECHNICAL: 'technical',
  FIRST_INTERVIEW_ROUND: 'first interview round',
  PRACTICAL: 'practical',
  CLIENT: 'client',

  SOFTWARE_ENGINEER: 'Software Engineer',
  WEB_DESIGNER: 'Web Designer',
  WEB_DEVELOPER: 'web Developer',
  FRONTED_DEVLOPER: 'Frontend Developer',
  SENIOR_FRONTED_DEVLOPER: 'Senior Frontend Developer',
  SENIOR_SOFTWARE_ENGINEER: 'Senior Software Engineer',
  APPLICATION_DEVELOPMENT_MODERNIZATION: 'Application Development Modernization',
  BACKEND_DEVLOPER: 'Backend Developer',
  JUNIOR_SOFTWARE_ENGINEER: 'Junior Software Engineer',
  FULL_STACK_DEVLOPER: 'Full Stack Developer',
  BLOCKCHAIN_DEVELOPER: 'Blockchain Developer',
  DATA_ANALYST: 'Data Analyst',
  DATA_SCIENTIST: 'Data Scientist',
  PRODUCT_MANAGER: 'Product Manager',
  PROJECT_ENGINEER: 'Project Engineer',
  UI_UX: 'UI_UX Designer',
  APPLICATION_DEVELOPER: 'Application developer',
  QA: 'QA Engineer',
  TECHNICAL_ANALYST: 'Technical Analyst',
  QUALITY_ANALYST: 'Quality Analyst',
  DEVOPS: 'DevOps Engineer',
  BUSNESS_ANALYST: 'Business Analyst',
  TECHNICSL_SUPPORT: 'Technical Support Engineer',
  JUNIOR_MERN_STACK_DEVELOPER: 'Junior MERN Stack Developer',
  MERN_STACK_DEVELOPER: 'MERN Stack Developer',
  MEAN_STACK_DEVELOPER: 'MEAN Stack Developer',
  DOTNET_DEVELOPER: 'DotNet Developer',
  JUNIOR_DOTNET_DEVELOPER: 'Junior DotNet develpoer',
  SENIOR_DOTNET_DEVELOPER: 'Senior DotNet develpoer',
  JAVA_DEVELOPER: 'Java Developer',
  PYTHON_DEVELOPER: 'Python Developer',
  PHP_DEVELOPER: 'PHP Developer',
  FRESHER: 'Fresher',
  SPECIALIST_PROGRAMMER: 'Specialist Programmer',
  REACT_DEVELOPER: 'React.js Developer',
  REACT_NATIVE_DEVELOPER: 'React Native Developer',
  NODEJS_DEVELOPER: 'Node.js Developer',
  SENIOR_JAVSCRIPT_DEVELOPER: 'Senior JavaScript Developer',
  ASSOCIATE_SOFTWARE_ENGINEER: 'Associate Software Engineer',
  ASSOCIATE_PROCESS_MANAGER: 'Associate Process Manager',
  FREELANCER: 'Freelancer',
  TEAM_LEADER: 'Team Leader',
  SENIOR_ANGULAR_DEVELOPER: 'Senior Angular Developer',
  SHAREPOINT_DEVELOPER: 'SharePoint Developer',
  OTHER: 'Other',
  NA: 'Na',
  SINGLE: 'Single',
  MARRIED: 'Married',
  MANUAL: 'Manual',
  CSV: 'Csv',
  RESUME: 'Resume'
};

export const skillGroupEnum = {
  FRONTEND:'Frontend',
  BACKEND:'Backend',
  DATABASE:'Database',
  TESTING:'Testing',
  DEVOPS:'devops',
  PROGRAMMING:'Programming',
  VERSION_CONTROL:'VersionControl',
  UI_UX:'UIUX',
  OTHERS:'Othersab',
}
