export const Enum = {
  ADMIN: 'admin',
  HR: 'hr',
  USER: 'user',
};
export const genderEnum = {
  MALE: 'male',
  FEMALE: 'female',
  OTHER: 'other',
};

export const jodTypeEnum = {
  FULL_TIME: 'full-time',
  PART_TIME: 'part-time',
  CONTRACT: 'contract',
  INTERNSHIP: 'internship',
  FREELANCE: 'freelance'
}
export const timeZome = {
  IST: 'IST',
  UTC: 'UTC',
  EST: 'EST'
}

export const applicantEnum = {
  YES: 'yes',
  NO: 'no',
  REMOTE: 'remote',
  HYBRID: 'hybrid',
  ONSITE: 'onsite',
  PENDING: 'pending',
  SELECTED: 'selected',
  REJECTED: 'rejected',
  HOLD: 'hold',
  IN_PROCESS: 'in-process',
  HR_ROUND: 'hr round',
  TECHNICAL: 'technical',
  FIRST_INTERVIEW_ROUND: 'first interview round',
  PRACTICAL: 'practical',
  CLIENT: 'client',

  SOFTWARE_ENGINEER: 'Software Engineer',
  WEB_DESIGNER: 'Web Designer',
  WEB_DEVELOPER: 'web Developer',
  FRONTED_DEVLOPER: 'Frontend Developer',
  SENIOR_FRONTED_DEVLOPER: 'Senior Frontend Developer',
  SENIOR_SOFTWARE_ENGINEER: 'Senior Software Engineer',
  APPLICATION_DEVELOPMENT_MODERNIZATION: 'Application Development Modernization',
  BACKEND_DEVLOPER: 'Backend Developer',
  JUNIOR_SOFTWARE_ENGINEER: 'Junior Software Engineer',
  FULL_STACK_DEVLOPER: 'Full Stack Developer',
  BLOCKCHAIN_DEVELOPER: 'Blockchain Developer',
  DATA_ANALYST: 'Data Analyst',
  DATA_SCIENTIST: 'Data Scientist',
  PRODUCT_MANAGER: 'Product Manager',
  PROJECT_ENGINEER: 'Project Engineer',
  UI_UX: 'UI_UX Designer',
  SENIOR_UI_ENGINEER: 'Senior UI Engineer',
  APPLICATION_DEVELOPER: 'Application developer',
  QA: 'QA Engineer',
  TECHNICAL_ANALYST: 'Technical Analyst',
  QUALITY_ANALYST: 'Quality Analyst',
  DEVOPS: 'DevOps Engineer',
  BUSNESS_ANALYST: 'Business Analyst',
  TECHNICSL_SUPPORT: 'Technical Support Engineer',
  JUNIOR_MERN_STACK_DEVELOPER: 'Junior MERN Stack Developer',
  MERN_STACK_DEVELOPER: 'MERN Stack Developer',
  MEAN_STACK_DEVELOPER: 'MEAN Stack Developer',
  DOTNET_DEVELOPER: 'DotNet Developer',
  JUNIOR_DOTNET_DEVELOPER: 'Junior DotNet developer',
  SENIOR_DOTNET_DEVELOPER: 'Senior DotNet developer',
  JAVA_DEVELOPER: 'Java Developer',
  PYTHON_DEVELOPER: 'Python Developer',
  PHP_DEVELOPER: 'PHP Developer',
  FRESHER: 'Fresher',
  SPECIALIST_PROGRAMMER: 'Specialist Programmer',
  REACT_DEVELOPER: 'Reactjs Developer',
  REACT_NATIVE_DEVELOPER: 'React Native Developer',
  NODEJS_DEVELOPER: 'Nodejs Developer',
  SENIOR_JAVSCRIPT_DEVELOPER: 'Senior JavaScript Developer',
  ASSOCIATE_SOFTWARE_ENGINEER: 'Associate Software Engineer',
  ASSOCIATE_PROCESS_MANAGER: 'Associate Process Manager',
  FREELANCER: 'Freelancer',
  TEAM_LEADER: 'Team Leader',
  SENIOR_ANGULAR_DEVELOPER: 'Senior Angular Developer',
  SHAREPOINT_DEVELOPER: 'SharePoint Developer',
  PLACEMENT_EXECUTIVE: 'Placement executive',
  SYSTEM_ENGINEER: 'System Engineer',
  SENIOR_SYSTEM_ENGINEER: 'Senior System Engineer',
  PROGRAMER_ANALYST: 'Programmer Analyst',
  CUSTOMER_SUPPORT_SPECIALIST: 'Customer Support Specialist',
  OTHER: 'Other',
  NA: 'Na',
  SINGLE: 'Single',
  MARRIED: 'Married',
  MANUAL: 'Manual',
  CSV: 'Csv',
  RESUME: 'Resume',
  GUEST: 'Guest'
};

export const candidateTemplateType = {
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  SHORTLISTED_FOR_INTERVIEW: 'SHORTLISTED_FOR_INTERVIEW',
  INTERVIEW_INVITATION: 'INTERVIEW_INVITATION',
  INTERVIEW_RESCHEDULE: 'INTERVIEW_RESCHEDULE',
  JOB_OFFER: 'JOB_OFFER',
  OFFER_ACCEPTANCE_CONFIRMATION: 'OFFER_ACCEPTANCE_CONFIRMATION',
  REJECTION_AFTER_INTERVIEW: 'REJECTION_AFTER_INTERVIEW',
  GENERAL_REJECTION: 'GENERAL_REJECTION',
  ONBOARDING_REMINDER: 'ONBOARDING_REMINDER',
  THANK_YOU_FOR_INTERVIEW: 'THANK_YOU_FOR_INTERVIEW',
};

